language: android

jdk:
  - oraclejdk8

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-28.0.3
  - echo y | android update sdk -u -a -t android-28
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-support
  - echo y | android update sdk -u -a -t extra-google-google_play_services

script:
  - ./gradlew lint
  - ./gradlew checkstyle
  - ./gradlew pmd
  - ./gradlew test -i


